apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-node
  template:
    metadata:
      labels:
        app: my-node
    spec:
      containers:
        - name: my-node-container
          image: akshatdhub26/my-node-app:latest
          imagePullPolicy: IfNotPresent    # this will prevent the pull from docker hub if present locally
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "root"
            - name: DB_NAME
              value: "testdb" 
